### ISSUE TITLE
Bug: Changing username leads to 404

### ISSUE THREAD

**Issue by JacobCoffee** [dcramer/peated#102]
Reproduce
1. New account
2. Change username
3. Click save
4. Go to the top right profile link
5. Click, 404
6. See that the href is the only one
	<img width="228" alt="image" src="https://github.com/dcramer/peated/assets/45884264/9c0fdb78-295a-4d0c-8002-078d7c42d78c">
7. Manually browse to `https://peated.com/users/$new_username`
8. $$$

**Comment by dcramer** [comment]
Need to repro in production, but maybe this coincidentally fixed itself with the tRPC conversion. I dont _think_ the code paths should have changed to re-bind the current session data, but it at least appears to work in dev for me. I tried real quick on prod and it seemed to work too. Possible there's more to it than this, but at least for now we'll assume this was fixed w/ the massive API rewrite.
