### ISSUE TITLE
Error when creating a bottle

### ISSUE THREAD

**Issue by garand** [dcramer/peated#103]
I tried to create a bottle and was getting this error.

It seems like maybe I don't have access to create bottles, or maybe something else is going on.

```
[{
    "error": {
        "message": "UNAUTHORIZED",
        "code": -32001,
        "data": {
            "code": "UNAUTHORIZED",
            "httpStatus": 401,
            "path": "bottleCreate"
        }
    }
}]
```

**Comment by dcramer** [comment]
I will double check the sentry error to make sure some of the details (praying it’s got em!), but were you logged in?

**Comment by garand** [comment]
Yeah. I just went back in and did it again, and it worked. 👍 But I was logged in before too.

**Comment by dcramer** [comment]
https://peated.sentry.io/share/issue/4edacdea27684c1e81683d87360f1c50/

Sentry error though nothing to learn from it really. Probably not too bad to reproduce. 

Thanks for the report!

**Comment by garand** [comment]
No worries! Would be neat to have the bottle avg price show in the list of bottles, not sure if there's a good way to get that, or maybe just user sourced.

**Comment by dcramer** [comment]
Think I figured out what happened in your case and should be squashed now 🙏
