### ISSUE TITLE
Issue : Docker-Compose not found 

### ISSUE THREAD

**Issue by rufevean** [dcramer/peated#127]
Description:
When attempting to start the development server by running docker-compose up -d, it was observed that the correct command for execution is docker compose up -d.

Steps to Reproduce:

    Clone the repository.
    Attempt to start the development server using docker-compose up -d.
    Observe the error message indicating that 'docker-compose' is not found.

Expected Behavior:
The provided command (docker-compose up -d) should work consistently across environments without reporting 'docker-compose not found' errors.

Proposed Solution:
Update the documentation to reflect the correct command (docker compose up -d) and investigate the underlying issue causing the 'docker-compose not found' error. This could involve ensuring that Docker and Docker Compose are properly installed and accessible in the environment.

**Comment by dcramer** [comment]
TIL - wonder when they exposed this on the core Docker binary. Looks fine on my system so guessing we can just straight up change it to be 'docker compose' going forward.
